# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_primary_color_is_ok works", {
  expect_error(
    object = check_primary_color_is_ok(string = c("Gray", "Pink", "Black", NA)),
    regexp = "Some colors do not match the required colors."
  )
  expect_true(
     check_primary_color_is_ok(string = c("Gray", "Cinnamon", "Black", NA))
  )
})
