# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

#' Checks if the primary color is ok
#' 
#' Checks if the primary color matches the required colors.
#' 
#' @param string A character vector. The colors of the squirrels.
#'
#' @return A boolean. TRUE if the colors are ok FALSE if they are not.
#' 
#' @export
#' 
#' @examples
#' check_primary_color_is_ok(string = c("Gray", "Cinnamon", "Black", NA))
#' # check_primary_color_is_ok(string = c("Gray", "Pink", "Black", NA))
check_primary_color_is_ok <- function(string) {
  all_colors_OK <- all(
    string %in% c("Gray", "Cinnamon", "Black", NA)
  )
  
  if (!all_colors_OK) {
    stop("Some colors do not match the required colors.")
  }
  
  return(all_colors_OK)
}
