# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' Get a message with primary fur color
#'
#' @param primary_fur_color A character string including (oh surprise) a 
#' primary fur color name.
#'
#' @return Nothing. It is used for its side effect of displaying a message.
#' 
#' @importFrom glue glue 
#' @export
#'
#' @examples
#' get_message_fur_color(primary_fur_color = "Cinnamon")
get_message_fur_color <- function(primary_fur_color){
  message(
    glue("We will focus on {primary_fur_color} squirrels")
  )
}
